version: '2'
services:
  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=dan2021
      - POSTGRES_USER=dan2021
      - POSTGRES_PASSWORD=dan2021
    ports:
      - "5432:5432"
    networks:
      - infra
      - app

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - infra

  artemis:
    container_name: artemis
    image: artemis:1.0.0
    restart: always
    ports:
      - "61616:61616"
    networks:
      - app
      - infra

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.6.1
    ports:
      - "9090:9090"
    volumes:
      - ./scripts/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      - app
  #      monitoring:
  #        aliases:
  #          - prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:6.5.0
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - app
      - infra

  service-discovery:
    container_name: service-discovery
    image: dan/service-discovery:1.0.0
    ports:
      - "8761:8761"
    networks:
      - app

  service-gateway:
    container_name: service-gateway
    image: dan/service-gateway:1.0.0
    ports:
      - "8181:8181"
    environment:
      - "SERVER_PORT=8181"
      - "DISCOVERY-SERVICE-URL=service-discovery:8761"
    networks:
      - app
      - infra

  ms-cuentacorriente:
    container_name: ms-cuentacorriente
    image: dan/ms-cuentacorriente:1.0.0
    ports:
      - "9003:9003"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SERVER_PORT=9003"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/dan2021?currentSchema=ms_cuentacorriente"
      - "SPRING_DATA_MONGODB_URI=mongodb://dan2021:dan2021@mongodb:27017/dan2021"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka"
    networks:
      - app

  ms-liquidacion:
    container_name: ms-liquidacion
    image: dan/ms-liquidacion:1.0.0
    ports:
      - "9004:9004"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SERVER_PORT=9002"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/dan2021?currentSchema=ms_pedido"
      - "SPRING_DATA_MONGODB_URI=mongodb://dan2021:dan2021@mongodb:27017/dan2021"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka"
    networks:
      - app

  ms-pedido:
    container_name: ms-pedido
    image: dan/ms-pedido:1.0.0
    ports:
      - "9002:9002"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SERVER_PORT=9002"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/dan2021?currentSchema=ms_pedido"
      - "SPRING_DATA_MONGODB_URI=mongodb://dan2021:dan2021@mongodb:27017/dan2021"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka"
      - "SPRING_ARTEMIS_HOST=artemis"
      - "SPRING_ARTEMIS_PORT=61616"
    networks:
      - app

  ms-producto:
    container_name: ms-producto
    image: dan/ms-producto:1.0.0
    ports:
      - "9001:9001"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SERVER_PORT=9001"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/dan2021?currentSchema=ms_producto"
      - "SPRING_DATA_MONGODB_URI=mongodb://dan2021:dan2021@mongodb:27017/dan2021"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka"
      - "SPRING_ARTEMIS_HOST=artemis"
      - "SPRING_ARTEMIS_PORT=61616"
    networks:
      - app

  ms-usuario:
    container_name: ms-usuario
    image: dan/ms-usuario:1.0.0
    ports:
      - "9000:9000"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SERVER_PORT=9000"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/dan2021?currentSchema=ms_usuario"
      - "SPRING_DATA_MONGODB_URI=mongodb://dan2021:dan2021@mongodb:27017/dan2021"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka"
    networks:
      - app

networks:
  infra:
    driver: bridge
  app:
    driver: bridge
